In [1]:
import numpy as np
import torch

In [30]:
# 행렬 코딩         
A = torch.tensor([[3, 1, 1], [1, -2, -1], [1, 1, 1]], dtype=torch.float)
print(A)
print(A.shape)

tensor([[ 3.,  1.,  1.],
        [ 1., -2., -1.],
        [ 1.,  1.,  1.]])
torch.Size([3, 3])


In [31]:
# 벡터 코딩
B = torch.tensor([4, 1, 2], dtype=torch.float)
print(B)
print(B.shape)  

tensor([4., 1., 2.])
torch.Size([3])


In [32]:
# 역행렬 구하기
a_u = torch.inverse(A)
print(a_u)
print(a_u.shape)

tensor([[ 5.0000e-01, -9.9341e-09, -5.0000e-01],
        [ 1.0000e+00, -1.0000e+00, -2.0000e+00],
        [-1.5000e+00,  1.0000e+00,  3.5000e+00]])
torch.Size([3, 3])


In [33]:
# Ax = B의 해 구하기
x = a_u @ B
print(x)

tensor([ 1., -1.,  2.])
