### Numpy의 연산

벡터와 스칼라의 연산

In [2]:
 import numpy as np
 x = np.array([1, 2, 3])
 c = 5
 print(f"더하기 = {x + c}")
 print(f"빼기 = {x - c}")
 print(f"나누기 = {x / c}")

더하기 = [6 7 8]
빼기 = [-4 -3 -2]
나누기 = [0.2 0.4 0.6]


벡터와 벡터 사이의 연산

In [11]:
x = np.array([1, 3, 5])
y = np.array([2, 9, 20])
print(f"더하기 = {x+y}")
print(f"빼기 = {x-y}")
print(f"나누기 = {x/y}")
print(f"곱하기 = {x*y}")

더하기 = [ 3 12 25]
빼기 = [ -1  -6 -15]
나누기 = [0.5        0.33333333 0.25      ]
곱하기 = [  2  27 100]


Array의 indexing

In [22]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x[0, 0]) # 1행 1열
print(x[2, 3]) # 3행 4열

1
12


In [21]:
## Array Slicing
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x[0][1:3]) # 2, 3 슬라이싱
print(x[1][1:3]) # 6, 7 슬라이싱

[2 3]
[6 7]


### Array의 Broadcasting
    - 1. M*N, M*1
        M*1 행렬이 N개의 열로 복제돼 수행한다.
    - 2. M*N, 1*N
        1*N 행렬이 M개의 행으로 복제돼 수행한다.


In [28]:
## 1번
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([0, 1, 0])
print(x+y)

# 2번
y = np.array([0, 1, -1])
print(x+y)

[[1 3 3]
 [4 6 6]
 [7 9 9]]
[[1 3 2]
 [4 6 5]
 [7 9 8]]


#### Numpy와 선형대수

영벡터

In [36]:
np.zeros(3)

array([0., 0., 0.])

In [37]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

일벡터

In [38]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

대각행렬

In [43]:
np.diag((2, 4))

array([[2, 0],
       [0, 4]])

In [44]:
np.diag((1, 3, 5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

항등행렬

In [47]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [50]:
# 디폴트는 float type이다
np.eye(3, dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

행렬곱(dot-product)

In [54]:
mat_1 = np.array([[1, 4], [2, 3]])
mat_2 = np.array([[7, 9], [0, 6]])
mat_1.dot(mat_2)
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

Trace: main diag의 합

In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.trace()

15

In [56]:
np.eye(2).trace()

2.0

행렬식(Determinant), 행렬을 대표하는 값

In [58]:
x = np.array([[2, 3], [1, 6]], dtype=int)
np.linalg.det(x)

9.000000000000002

역행렬

In [60]:
x = np.array([[2, 3], [1, 6]], dtype=int)
x_inv = np.linalg.inv(x)
x @ x_inv

array([[1., 0.],
       [0., 1.]])

고유값과 고유 벡터

In [62]:
x = np.array([[2, 3], [1, 6]], dtype=int)
np.linalg.eig(x)

(array([1.35424869, 6.64575131]),
 array([[-0.97760877, -0.54247681],
        [ 0.21043072, -0.84007078]]))